## Import necessary module

In [122]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import r2_score
import seaborn as sb
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import confusion_matrix

### Reading dataset

In [123]:
df=pd.read_csv(r'C:\Graduate Courses\Spring 2020\Homework_3\Game_data\Game.csv',error_bad_lines=False)

In [124]:
df

ID        Date             Opponent  Is_Home_o r_Away  \
0    1    9/5/2015                Texas             Home    
1    2   9/12/2015             Virginia             Away    
2    3   9/19/2015         GeorgiaTec h             Home    
3    4   9/26/2015                UMass             Home    
4    5   10/3/2015              Clemson             Away    
5    6  10/10/2015                 Navy             Home    
6    7  10/17/2015                  USC             Home    
7    8  10/31/2015               Temple             Away    
8    9   11/7/2015                 PITT             Away    
9   10  11/14/2015            WakeForest            Home    
10  11  11/21/2015       BostonColl ege             Away    
11  12  11/28/2015             Stanford             Away    
12  13    9/4/2016                Texas             Away    
13  14   9/10/2016               Nevada             Home    
14  15   9/17/2016       MichiganSt ate             Home    
15  16   9/24/2016                 Duke             Home    
16  17   10/1/2016             Syracuse             Home    
17  18   10/8/2016  NorthCaroli naState             Away    
18  19  10/15/2016             Stanford             Home    
19  20  10/29/2016        MiamiFlori da             Home    
20  21   11/5/2016                 Navy             Home    
21  22  11/12/2016                 Army             Home    
22  23  11/19/2016        VirginiaTec h             Home    
23  24  11/26/2016                  USC             Away    
24  25    9/2/2017               Temple             Home    
25  26    9/9/2017              Georgia             Home    
26  27   9/16/2017       BostonColleg e             Away    
27  28   9/23/2017       MichiganStat e             Away    
28  29   9/30/2017            MiamiOhio             Home    
29  30   10/7/2017       NorthCarolin a             Away    
30  31  10/21/2017                  USC             Home    
31  32  10/28/2017  NorthCarolin aState             Home    
32  33   11/4/2017           WakeForest             Home    
33  34  11/11/2017         MiamiFlorida             Away    
34  35  11/18/2017                 Navy             Home    
35  36  11/25/2017             Stanford             Away    

   Is_Oppone nt_in_AP25 _Preseason    Media  Label  
0                             Out    1-NBC    Win   
1                             Out    4-ABC    Win   
2                              In    1-NBC    Win   
3                             Out    1-NBC    Win   
4                              In    4-ABC   Lose   
5                             Out    1-NBC    Win   
6                              In    1-NBC    Win   
7                             Out    4-ABC    Win   
8                             Out    4-ABC    Win   
9                             Out    1-NBC    Win   
10                            Out    1-NBC    Win   
11                             In    3-FOX   Lose   
12                            Out    4-ABC   Lose   
13                            Out    1-NBC    Win   
14                            Out    1-NBC   Lose   
15                            Out    1-NBC   Lose   
16                            Out   2-ESPN    Win   
17                            Out    4-ABC   Lose   
18                             In    1-NBC   Lose   
19                            Out    1-NBC    Win   
20                            Out    5-CBS   Lose   
21                            Out    1-NBC    Win   
22                             In    1-NBC   Lose   
23                             In    4-ABC   Lose   
24                            Out    1-NBC    Win   
25                             In    1-NBC   Lose   
26                            Out   2-ESPN    Win   
27                            Out    3-FOX    Win   
28                            Out    1-NBC    Win   
29                            Out    4-ABC    Win   
30                             In    1-NBC    Win   
31                            Out    1-NBC    Win 

In [125]:
df.columns

Index(['ID', 'Date', 'Opponent ', 'Is_Home_o r_Away',
       'Is_Oppone nt_in_AP25 _Preseason', 'Media', 'Label'],
      dtype='object')

In [126]:
np.array(df.Label)

array(['Win ', 'Win ', 'Win ', 'Win ', 'Lose ', 'Win ', 'Win ', 'Win ',
       'Win ', 'Win ', 'Win ', 'Lose ', 'Lose ', 'Win ', 'Lose ', 'Lose ',
       'Win ', 'Lose ', 'Lose ', 'Win ', 'Lose ', 'Win ', 'Lose ',
       'Lose ', 'Win ', 'Lose ', 'Win ', 'Win ', 'Win ', 'Win ', 'Win ',
       'Win ', 'Win ', 'Lose ', 'Win ', 'Lose '], dtype=object)

In [127]:
print(list(df['Label']))

['Win ', 'Win ', 'Win ', 'Win ', 'Lose ', 'Win ', 'Win ', 'Win ', 'Win ', 'Win ', 'Win ', 'Lose ', 'Lose ', 'Win ', 'Lose ', 'Lose ', 'Win ', 'Lose ', 'Lose ', 'Win ', 'Lose ', 'Win ', 'Lose ', 'Lose ', 'Win ', 'Lose ', 'Win ', 'Win ', 'Win ', 'Win ', 'Win ', 'Win ', 'Win ', 'Lose ', 'Win ', 'Lose ']


In [128]:
data_features_name = ['Is_Home_o r_Away','Is_Oppone nt_in_AP25 _Preseason', 'Media']

In [129]:
print(df['Is_Home_o r_Away'].unique())

print(df['Is_Oppone nt_in_AP25 _Preseason'].unique())

print(df['Media'].unique())

print(df['Label'].unique())


['Home ' 'Away ']
['Out ' 'In ']
['1-NBC ' '4-ABC ' '3-FOX ' '2-ESPN ' '5-CBS ']
['Win ' 'Lose ']


### Data Processing/ feature Engineering 

In [130]:
df['Is_Home_o r_Away'] = df['Is_Home_o r_Away'].map({'Home ':1,'Away ':2}).astype(int)
df['Is_Oppone nt_in_AP25 _Preseason'] = df['Is_Oppone nt_in_AP25 _Preseason'].map({'Out ':2,'In ':1}).astype(int)
df['Media'] = df['Media'].map({'1-NBC ': 1, '4-ABC ':4, '3-FOX ':3, '2-ESPN ':2, '5-CBS ':5}).astype(int)
df['Label'] = df['Label'].map({'Win ': 1, 'Lose ':2}).astype(int)

In [131]:
print(list(df['Media']))

[1, 4, 1, 1, 4, 1, 1, 4, 4, 1, 1, 3, 4, 1, 1, 1, 2, 4, 1, 1, 5, 1, 1, 4, 1, 1, 2, 3, 1, 4, 1, 1, 1, 4, 1, 4]


In [132]:
df

ID        Date             Opponent   Is_Home_o r_Away  \
0    1    9/5/2015                Texas                  1   
1    2   9/12/2015             Virginia                  2   
2    3   9/19/2015         GeorgiaTec h                  1   
3    4   9/26/2015                UMass                  1   
4    5   10/3/2015              Clemson                  2   
5    6  10/10/2015                 Navy                  1   
6    7  10/17/2015                  USC                  1   
7    8  10/31/2015               Temple                  2   
8    9   11/7/2015                 PITT                  2   
9   10  11/14/2015            WakeForest                 1   
10  11  11/21/2015       BostonColl ege                  2   
11  12  11/28/2015             Stanford                  2   
12  13    9/4/2016                Texas                  2   
13  14   9/10/2016               Nevada                  1   
14  15   9/17/2016       MichiganSt ate                  1   
15  16   9/24/2016                 Duke                  1   
16  17   10/1/2016             Syracuse                  1   
17  18   10/8/2016  NorthCaroli naState                  2   
18  19  10/15/2016             Stanford                  1   
19  20  10/29/2016        MiamiFlori da                  1   
20  21   11/5/2016                 Navy                  1   
21  22  11/12/2016                 Army                  1   
22  23  11/19/2016        VirginiaTec h                  1   
23  24  11/26/2016                  USC                  2   
24  25    9/2/2017               Temple                  1   
25  26    9/9/2017              Georgia                  1   
26  27   9/16/2017       BostonColleg e                  2   
27  28   9/23/2017       MichiganStat e                  2   
28  29   9/30/2017            MiamiOhio                  1   
29  30   10/7/2017       NorthCarolin a                  2   
30  31  10/21/2017                  USC                  1   
31  32  10/28/2017  NorthCarolin aState                  1   
32  33   11/4/2017           WakeForest                  1   
33  34  11/11/2017         MiamiFlorida                  2   
34  35  11/18/2017                 Navy                  1   
35  36  11/25/2017             Stanford                  2   

    Is_Oppone nt_in_AP25 _Preseason  Media  Label  
0                                 2      1      1  
1                                 2      4      1  
2                                 1      1      1  
3                                 2      1      1  
4                                 1      4      2  
5                                 2      1      1  
6                                 1      1      1  
7                                 2      4      1  
8                                 2      4      1  
9                                 2      1      1  
10                                2      1      1  
11                                1      3      2  
12                                2      4      2  
13                                2      1      1  
14                                2      1      2  
15                                2      1      2  
16                                2      2      1  
17                                2      4      2  
18                                1      1      2  
19                                2      1      1  
20                                2      5      2  
21                                2      1      1  
22                                1      1      2  
23                                1      4      2  
24                                2      1      1  
25                                1      1      2  
26                                2      2      1  
27                                2      3      1  
28                                2      1      1  
29                                2      4      1  
30                                1      1      1  
31                                2      1   

In [133]:
#df.to_csv(r"C:\Graduate Courses\Spring 2020\Homework_3\Game_data\Game_R.csv")

### Saving the processed data

In [134]:
df.to_csv('game_df.csv')

In [135]:
np.array(df['Label'])

array([1, 1, 1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 1, 2, 2, 1, 2, 2, 1, 2, 1,
       2, 2, 1, 2, 1, 1, 1, 1, 1, 1, 1, 2, 1, 2])

### Test Train split

In [136]:
train_df=df[df['ID']<=24]

In [137]:
train_df

ID        Date             Opponent   Is_Home_o r_Away  \
0    1    9/5/2015                Texas                  1   
1    2   9/12/2015             Virginia                  2   
2    3   9/19/2015         GeorgiaTec h                  1   
3    4   9/26/2015                UMass                  1   
4    5   10/3/2015              Clemson                  2   
5    6  10/10/2015                 Navy                  1   
6    7  10/17/2015                  USC                  1   
7    8  10/31/2015               Temple                  2   
8    9   11/7/2015                 PITT                  2   
9   10  11/14/2015            WakeForest                 1   
10  11  11/21/2015       BostonColl ege                  2   
11  12  11/28/2015             Stanford                  2   
12  13    9/4/2016                Texas                  2   
13  14   9/10/2016               Nevada                  1   
14  15   9/17/2016       MichiganSt ate                  1   
15  16   9/24/2016                 Duke                  1   
16  17   10/1/2016             Syracuse                  1   
17  18   10/8/2016  NorthCaroli naState                  2   
18  19  10/15/2016             Stanford                  1   
19  20  10/29/2016        MiamiFlori da                  1   
20  21   11/5/2016                 Navy                  1   
21  22  11/12/2016                 Army                  1   
22  23  11/19/2016        VirginiaTec h                  1   
23  24  11/26/2016                  USC                  2   

    Is_Oppone nt_in_AP25 _Preseason  Media  Label  
0                                 2      1      1  
1                                 2      4      1  
2                                 1      1      1  
3                                 2      1      1  
4                                 1      4      2  
5                                 2      1      1  
6                                 1      1      1  
7                                 2      4      1  
8                                 2      4      1  
9                                 2      1      1  
10                                2      1      1  
11                                1      3      2  
12                                2      4      2  
13                                2      1      1  
14                                2      1      2  
15                                2      1      2  
16                                2      2      1  
17                                2      4      2  
18                                1      1      2  
19                                2      1      1  
20                                2      5      2  
21                                2      1      1  
22                                1      1      2  
23                                1      4      2

In [138]:
test_df=df[df['ID']>24]

In [139]:
X_train=train_df.filter(['Is_Home_o r_Away','Is_Oppone nt_in_AP25 _Preseason', 'Media'])
Y_train=train_df['Label']

### Model Development

In [140]:
#spliting data_set into test and train set and fit into decision Tree
clf_NB = GaussianNB()
clf_NB.fit(X_train, Y_train)
print("Accuracy on training set: {:.3f}".format(clf_NB.score(X_train, Y_train)))

Accuracy on training set: 0.708


### Model Accuracy 

In [141]:
X_test=test_df.filter(['Is_Home_o r_Away','Is_Oppone nt_in_AP25 _Preseason', 'Media'])
Y_test=test_df['Label']

In [142]:
print("Accuracy on test set: {:.3f}".format(clf_NB.score(X_test, Y_test)))
Y_pred=clf_NB.predict(X_test)
print(Y_pred)

Accuracy on test set: 0.833
[1 2 1 1 1 2 2 1 1 2 1 2]


### Accuracy metrics estimation

In [148]:
from sklearn.metrics import classification_report

In [149]:
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           1       1.00      0.78      0.88         9
           2       0.60      1.00      0.75         3

    accuracy                           0.83        12
   macro avg       0.80      0.89      0.81        12
weighted avg       0.90      0.83      0.84        12



In [150]:
confusion_matrix(Y_test, Y_pred)

array([[7, 2],
       [0, 3]], dtype=int64)

## Decision Tree ID3

In [152]:
clf_ID3 = DecisionTreeClassifier(criterion='entropy',max_depth=15, random_state=0)

clf_ID3.fit(X_train, Y_train)

print("Accuracy on training set: {:.3f}".format(clf_ID3.score(X_train, Y_train)))

Accuracy on training set: 0.750


In [153]:
print("Accuracy on test set: {:.3f}".format(clf_ID3.score(X_test, Y_test)))
Y_pred=clf_ID3.predict(X_test)
print(Y_pred)

Accuracy on test set: 0.917
[1 1 1 1 1 1 1 1 1 2 1 2]


In [154]:
confusion_matrix(Y_test, Y_pred)

array([[9, 0],
       [1, 2]], dtype=int64)

In [155]:
print(classification_report(Y_test, Y_pred))

              precision    recall  f1-score   support

           1       0.90      1.00      0.95         9
           2       1.00      0.67      0.80         3

    accuracy                           0.92        12
   macro avg       0.95      0.83      0.87        12
weighted avg       0.92      0.92      0.91        12



## R CODE for ploting C4.5 Tree

In [ ]:
library("partykit")
library("party")
library("caret")
library("RWeka")

## Reading data for three different problems

data<-data.frame("home_away"=c(1, 2, 1, 1, 2, 1, 1, 2, 2, 1, 2, 2, 2, 1, 1, 1, 1, 2, 1, 1, 1, 1,
       1, 2, 1, 1, 2, 2, 1, 2, 1, 1, 1, 2, 1, 2),"Media"=c(1, 4, 1, 1, 4, 1, 1, 4, 4, 1, 1, 3, 4, 1, 1, 1, 2, 4, 1, 1, 5, 1,
       1, 4, 1, 1, 2, 3, 1, 4, 1, 1, 1, 4, 1, 4),"label"=c('Win ', 'Win ', 'Win ', 'Win ', 'Lose ', 'Win ', 'Win ', 'Win ',
       'Win ', 'Win ', 'Win ', 'Lose ', 'Lose ', 'Win ', 'Lose ', 'Lose ',
       'Win ', 'Lose ', 'Lose ', 'Win ', 'Lose ', 'Win ', 'Lose ',
       'Lose ', 'Win ', 'Lose ', 'Win ', 'Win ', 'Win ', 'Win ', 'Win ',
       'Win ', 'Win ', 'Lose ', 'Win ', 'Lose '))

train <-data[1:24,]
test <-data[25:36,]

C45Fit <-J48(label ~., data= train)

plot(C45Fit1)

confusionMatrix(results, test$Label)
